name: cache-prime

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  prime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dir
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-810982b

      - name: prime-cache-810982b
        run: echo "cache_hit=${{ steps.cache.outputs.cache-hit }}"

      - name: Install deps
        run: npm install

